# Generated by Django 5.0 on 2023-12-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='type',
            field=models.IntegerField(choices=[(1, 'Propriétaire'), (2, 'Vendeur'), (3, 'Abonne')], default=1),
        ),
    ]
