# Generated by Django 5.0 on 2024-01-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240103_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateField(auto_now_add=True),
        ),
    ]
