# Generated by Django 5.0 on 2023-12-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_utilisateur_managers_utilisateur_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleur',
            old_name='id_famille',
            new_name='famille',
        ),
    ]
