# Generated by Django 5.0 on 2024-02-08 19:50

from django.db import migrations
from django.contrib.auth.hashers import make_password  # Importer la fonction make_password

def add_vendeur_proprietaire(apps, schema_editor):
    Utilisateur = apps.get_model('core', 'Utilisateur')

    # Ajouter le vendeur avec mot de passe haché
    vendeur = Utilisateur.objects.create(username='vendeur', password=make_password('vendeur@1234'), type=2)

    # Ajouter le proprietaire avec mot de passe haché
    proprietaire = Utilisateur.objects.create(username='proprietaire', password=make_password('proprietaire@1234'), type=1)



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fleur_code'),
    ]

    operations = [
        migrations.RunPython(add_vendeur_proprietaire),
    ]