# Generated by Django 5.0 on 2023-12-26 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_id_famille_fleur_famille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleur',
            name='famille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.famille'),
        ),
    ]
