# Generated by Django 5.0 on 2023-12-26 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fleur_famille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleur',
            name='famille',
            field=models.ForeignKey(blank=True, db_column='famille', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.famille'),
        ),
    ]
